# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RNTrueTime' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNTrueTime
  pod 'React', :path => './node_modules/react-native', :subspecs => [
  'Core',
  'CxxBridge' # Include this for RN >= 0.47
  ]
  # Yoga support for React Native
  pod 'yoga', :path => './node_modules/react-native/ReactCommon/yoga'
  # Required by CxxBridge
  pod 'Folly', :podspec => './node_modules/react-native/third-party-podspecs/Folly.podspec'
  # TrueTime
  pod 'TrueTime'
end
